/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package project;

import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author joshokeeffe
 */
public class AccountGUI extends javax.swing.JFrame {

    // declaring a new arraylist to hold the accounts
    private ArrayList<Account> accountList = new ArrayList<>();

    // declaring variables
    private static String firstName;
    private static String lastName;
    private static String email;
    private static String selectedCourse;
    private static String times;

    // constructor with parameters
    // this constructor is used when the user enters details from the SignupGUI and it passes those details as the parameters
    public AccountGUI(String firstName, String lastName, String email, String selectedCourse) {
        initComponents();

        // assigns the variables with the values passed to the constructor
        this.firstName = firstName;
        this.lastName = lastName;
        this.email = email;
        this.selectedCourse = selectedCourse;

        // update the labels with user details
        welcomeLbl.setText("Welcome, " + firstName);
        firstNameTxt.setText(firstName);
        lastNameTxt.setText(lastName);
        emailTxt.setText(email);
        courseTxt.setText(selectedCourse);
        timesTxt.setText(getCourseTimes(selectedCourse));

    }

    // this constructor is used when the user is signing in, and uses the account class to retrieve the users details
    public AccountGUI(Account account) {
        initComponents();
        
        // update the labels with user details
        welcomeLbl.setText("Welcome, " + account.getFirstName());
        firstNameTxt.setText(account.getFirstName());
        lastNameTxt.setText(account.getLastName());
        emailTxt.setText(account.getEmail());
        courseTxt.setText(account.getSelectedCourse());
        
        // calls the getCourseTimes and passes getSelectedCourse as the parameter
        timesTxt.setText(getCourseTimes(account.getSelectedCourse()));
    }

    // a function that takes the course name and returns the appropriate course times as a string
    public String getCourseTimes(String selectedCourse) {
        switch (selectedCourse) {
            case "Object Orientated Programming":
                return "Mon: 12:00-14:00, Tue: 10:00-12:00";
            case "Web Application Development":
                return "Wed: 14:00-16:00, Mon: 12:00-15:00";
            case "Advanced Databases":
                return "Tue: 10:00-13:00, Fri: 13:00-15:00";
            case "Data Communications & Networking":
                return "Thur: 12:00-15:00, Fri: 14:00-16:00";
            case "Cloud Computing":
                return "Wed: 16:00-18:00, Fri: 14:00-16:00";
            case "Artificial Intelligence":
                return "Tue: 14:00-16:00, Thu: 10:00-12:00";
            case "Internet of Things (IoT)":
                return "Tue: 12:00-14:00, Thu: 14:00-16:00";
            case "Software Testing and Quality Assurance":
                return "Wed: 10:00-12:00, Fri: 12:00-14:00";
            case "Mobile App Development":
                return "Mon: 16:00-18:00, Wed: 12:00-14:00";
            case "Cybersecurity Fundamentals":
                return "Tue: 16:00-18:00, Fri: 14:00-16:00";
            case "Software Engineering Principles":
                return "Thu: 12:00-14:00, Fri: 10:00-12:00";
            case "Machine Learning Fundamentals":
                return "Mon: 14:00-16:00, Thu: 16:00-18:00";
            default:
                return "No class times available";
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        welcomeLbl = new javax.swing.JLabel();
        firstNameLbl = new javax.swing.JLabel();
        userDetailsLbl = new javax.swing.JLabel();
        lastNameLbl = new javax.swing.JLabel();
        emailLbl = new javax.swing.JLabel();
        courseLbl = new javax.swing.JLabel();
        firstNameTxt = new javax.swing.JLabel();
        lastNameTxt = new javax.swing.JLabel();
        emailTxt = new javax.swing.JLabel();
        courseTxt = new javax.swing.JLabel();
        timesLbl = new javax.swing.JLabel();
        timesTxt = new javax.swing.JLabel();
        saveBtn = new javax.swing.JButton();
        navBar4 = new javax.swing.JMenuBar();
        homeF4 = new javax.swing.JMenu();
        homeItem4 = new javax.swing.JMenuItem();
        coursesF = new javax.swing.JMenu();
        coursesItem = new javax.swing.JMenuItem();
        signupMenu = new javax.swing.JMenuItem();
        loginItem = new javax.swing.JMenuItem();
        schoolF = new javax.swing.JMenu();
        applicationItem = new javax.swing.JMenuItem();
        donationItem = new javax.swing.JMenuItem();
        contactT = new javax.swing.JMenu();
        forum = new javax.swing.JMenuItem();
        volunteerT = new javax.swing.JMenu();
        volunteerItem = new javax.swing.JMenuItem();
        mathT = new javax.swing.JMenu();
        mathItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        welcomeLbl.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        welcomeLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        welcomeLbl.setText("Welcome");

        firstNameLbl.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        firstNameLbl.setText("First Name:");

        userDetailsLbl.setFont(new java.awt.Font("Helvetica Neue", 0, 20)); // NOI18N
        userDetailsLbl.setText("User Details");

        lastNameLbl.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        lastNameLbl.setText("Last Name:");

        emailLbl.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        emailLbl.setText("Email:");

        courseLbl.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        courseLbl.setText("Enrolled Course:");

        firstNameTxt.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N

        lastNameTxt.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N

        emailTxt.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N

        courseTxt.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N

        timesLbl.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        timesLbl.setText("Class Times:");

        timesTxt.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N

        saveBtn.setText("Save Details");
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });

        navBar4.setBackground(new java.awt.Color(204, 204, 255));

        homeF4.setText("Home");

        homeItem4.setText("Home");
        homeItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeItem4ActionPerformed(evt);
            }
        });
        homeF4.add(homeItem4);

        navBar4.add(homeF4);

        coursesF.setText("Courses");

        coursesItem.setText("Courses");
        coursesItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                coursesItemActionPerformed(evt);
            }
        });
        coursesF.add(coursesItem);

        signupMenu.setText("Sign Up");
        signupMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signupMenuActionPerformed(evt);
            }
        });
        coursesF.add(signupMenu);

        loginItem.setText("Log In");
        loginItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginItemActionPerformed(evt);
            }
        });
        coursesF.add(loginItem);

        navBar4.add(coursesF);

        schoolF.setText("School");

        applicationItem.setText("Application");
        applicationItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                applicationItemActionPerformed(evt);
            }
        });
        schoolF.add(applicationItem);

        donationItem.setText("Donation");
        donationItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                donationItemActionPerformed(evt);
            }
        });
        schoolF.add(donationItem);

        navBar4.add(schoolF);

        contactT.setText("Contact");

        forum.setText("Forum");
        forum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                forumActionPerformed(evt);
            }
        });
        contactT.add(forum);

        navBar4.add(contactT);

        volunteerT.setText("Volunteer");

        volunteerItem.setText("Volunteer Teacher");
        volunteerItem.setToolTipText("");
        volunteerItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volunteerItemActionPerformed(evt);
            }
        });
        volunteerT.add(volunteerItem);

        navBar4.add(volunteerT);

        mathT.setText("Math Game");

        mathItem.setText("Math Game");
        mathItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mathItemActionPerformed(evt);
            }
        });
        mathT.add(mathItem);

        navBar4.add(mathT);

        setJMenuBar(navBar4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(271, 271, 271)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(userDetailsLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(saveBtn)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(148, 148, 148)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(timesLbl)
                            .addComponent(courseLbl)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lastNameLbl)
                                .addComponent(firstNameLbl)
                                .addComponent(emailLbl, javax.swing.GroupLayout.Alignment.TRAILING)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(firstNameTxt)
                            .addComponent(lastNameTxt)
                            .addComponent(emailTxt)
                            .addComponent(courseTxt)
                            .addComponent(timesTxt))))
                .addContainerGap(263, Short.MAX_VALUE))
            .addComponent(welcomeLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(welcomeLbl)
                .addGap(18, 18, 18)
                .addComponent(userDetailsLbl)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firstNameLbl)
                    .addComponent(firstNameTxt))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lastNameLbl)
                    .addComponent(lastNameTxt))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailLbl)
                    .addComponent(emailTxt))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(courseLbl)
                    .addComponent(courseTxt))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(timesLbl)
                    .addComponent(timesTxt))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addComponent(saveBtn)
                .addGap(54, 54, 54))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // the save details button
    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        // creates a new instance of the account class, passing the appropriate variables as the parameters
        Account newAccount = new Account(firstName, lastName, email, selectedCourse);

        // adds the new account to accountList arraylist
        accountList.add(newAccount);

        // Write all accounts to the file
        try {
            // creates a new csv
            File file = new File("accountDetails.csv");
            
            // creates a filewriter object and sets the append mode to true,
            // so when the save button is pressed, 
            // it doesn't overwrite the previous file
            FileWriter fw = new FileWriter(file, true);
            
            // creates a bufferedwriter object that writes to filewriter
            BufferedWriter writer = new BufferedWriter(fw);

            // formats the output to csv format, separating each value with a ","
            String accountDetails = String.join(",",
                    newAccount.getFirstName(),
                    newAccount.getLastName(),
                    newAccount.getEmail(),
                    newAccount.getSelectedCourse()
            );

            // writes the formatted account details to the csv file
            writer.write(accountDetails);
            
            // moves to the next line of the file
            writer.newLine();

            // tells the user the file was updated
            JOptionPane.showMessageDialog(null, "File updated successfully.");
            
            // closes the buffered writer
            writer.close();
        } catch (IOException e) {
            // prints the error to the console
            System.out.println("Error writing to file: " + e);
        }

    }//GEN-LAST:event_saveBtnActionPerformed

    private void homeItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeItem4ActionPerformed
        // TODO add your handling code here:
        ProjectGUI appGUI = new ProjectGUI();

        // make the new ui appear
        appGUI.setVisible(true);

        // close the Project GUI
        this.dispose();
    }//GEN-LAST:event_homeItem4ActionPerformed

    private void coursesItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_coursesItemActionPerformed
        // TODO add your handling code here:
        CoursesGUI appGUI = new CoursesGUI();

        // make the new ui appear
        appGUI.setVisible(true);

        // close the Project GUI
        this.dispose();
    }//GEN-LAST:event_coursesItemActionPerformed

    private void signupMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signupMenuActionPerformed
        // creates a new instance of the Sign Up GUI
        SignupGUI newSignupGUI = new SignupGUI();

        // makes the new ui appear
        newSignupGUI.setVisible(true);

        // close the Project GUI
        this.dispose();
    }//GEN-LAST:event_signupMenuActionPerformed

    private void loginItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginItemActionPerformed

        // creates a new instance of the Sign Up GUI
        LoginGUI newLogin = new LoginGUI();

        // makes the new ui appear
        newLogin.setVisible(true);

        // close the Project GUI
        this.dispose();
    }//GEN-LAST:event_loginItemActionPerformed

    private void applicationItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_applicationItemActionPerformed
        // creates a new instance of the Application GUI
        ApplicationGUI newApp = new ApplicationGUI();

        // makes the new ui appear
        newApp.setVisible(true);

        // close the Project GUI
        this.dispose();
    }//GEN-LAST:event_applicationItemActionPerformed

    private void donationItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_donationItemActionPerformed
        // creates a new instance of the Donation GUI
        DonationGUI newDonation = new DonationGUI();

        // makes the new ui appear
        newDonation.setVisible(true);

        // close the Project GUI
        this.dispose();
    }//GEN-LAST:event_donationItemActionPerformed

    private void forumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_forumActionPerformed
        // creates a new instance of the feedback GUI
        feedbackGUI newFeedback = new feedbackGUI();

        // makes the new ui appear
        newFeedback.setVisible(true);

        // close the Project GUI
        this.dispose();
    }//GEN-LAST:event_forumActionPerformed

    private void volunteerItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volunteerItemActionPerformed
        // creates a new instance of the Sign Up GUI
        teacherGUI newTeacher = new teacherGUI();

        // makes the new ui appear
        newTeacher.setVisible(true);

        // close the Project GUI
        this.dispose();
    }//GEN-LAST:event_volunteerItemActionPerformed

    private void mathItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mathItemActionPerformed
        // creates a new instance of the Sign Up GUI
        mathGUI newMath = new mathGUI();

        // makes the new ui appear
        newMath.setVisible(true);

        // close the Project GUI
        this.dispose();
    }//GEN-LAST:event_mathItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AccountGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AccountGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AccountGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AccountGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AccountGUI(firstName, lastName, email, selectedCourse).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem applicationItem;
    private javax.swing.JMenu contactT;
    private javax.swing.JLabel courseLbl;
    private javax.swing.JLabel courseTxt;
    private javax.swing.JMenu coursesF;
    private javax.swing.JMenuItem coursesItem;
    private javax.swing.JMenuItem donationItem;
    private javax.swing.JLabel emailLbl;
    private javax.swing.JLabel emailTxt;
    private javax.swing.JLabel firstNameLbl;
    private javax.swing.JLabel firstNameTxt;
    private javax.swing.JMenuItem forum;
    private javax.swing.JMenu homeF4;
    private javax.swing.JMenuItem homeItem4;
    private javax.swing.JLabel lastNameLbl;
    private javax.swing.JLabel lastNameTxt;
    private javax.swing.JMenuItem loginItem;
    private javax.swing.JMenuItem mathItem;
    private javax.swing.JMenu mathT;
    private javax.swing.JMenuBar navBar4;
    private javax.swing.JButton saveBtn;
    private javax.swing.JMenu schoolF;
    private javax.swing.JMenuItem signupMenu;
    private javax.swing.JLabel timesLbl;
    private javax.swing.JLabel timesTxt;
    private javax.swing.JLabel userDetailsLbl;
    private javax.swing.JMenuItem volunteerItem;
    private javax.swing.JMenu volunteerT;
    private javax.swing.JLabel welcomeLbl;
    // End of variables declaration//GEN-END:variables
}
