/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package project;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import javax.swing.JOptionPane;
/**
 *
 * @author dongyiyoo
 */
public class UnsubscribeGUI extends javax.swing.JFrame {
     private ArrayList<Subscriber> subscriberList;
    /**
     * Creates new form Unsubscribe
     */
     // Constructor to receive the ArrayList from SubscribeGUI
    public UnsubscribeGUI(ArrayList<Subscriber> subscriberList) {
        initComponents();
        this.subscriberList = subscriberList;
        
        //Close only this window
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ThankLbl = new javax.swing.JLabel();
        SubscribeLbl = new javax.swing.JLabel();
        UnsubscribeBtn = new javax.swing.JButton();
        UnsubscribeLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ThankLbl.setFont(new java.awt.Font(".AppleSystemUIFont", 1, 36)); // NOI18N
        ThankLbl.setText("THANK YOU");

        SubscribeLbl.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 14)); // NOI18N
        SubscribeLbl.setText("You are now subscribed to our newsletter");

        UnsubscribeBtn.setText("Unsubscribe");
        UnsubscribeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UnsubscribeBtnActionPerformed(evt);
            }
        });

        UnsubscribeLbl.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 10)); // NOI18N
        UnsubscribeLbl.setForeground(new java.awt.Color(153, 153, 153));
        UnsubscribeLbl.setText("To unsubscribe click the button above");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(72, Short.MAX_VALUE)
                .addComponent(SubscribeLbl)
                .addGap(67, 67, 67))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(159, 159, 159)
                        .addComponent(UnsubscribeBtn))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addComponent(UnsubscribeLbl))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addComponent(ThankLbl)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(ThankLbl)
                .addGap(18, 18, 18)
                .addComponent(SubscribeLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(UnsubscribeBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(UnsubscribeLbl)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void UnsubscribeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UnsubscribeBtnActionPerformed
        // TODO add your handling code here:
        
        if(subscriberList.isEmpty()){
        JOptionPane.showMessageDialog(null, "Sorry, there are no subscriber information to delete.");
    } else {
        String searchTerm = JOptionPane.showInputDialog(null, "Please enter the email to delete:");
        
        boolean found = false;
        for(Subscriber s : subscriberList){
            if(s.getEmail().equalsIgnoreCase(searchTerm)){
                subscriberList.remove(s);
                JOptionPane.showMessageDialog(null,s.getDetails()+ " has been deleted.");
                found = true;
                break;  // if the email is found
            }
        }
        
        if(!found){
            JOptionPane.showMessageDialog(null, "No matching email found.");
        }
    } 
        File f;
        FileOutputStream fStream;
        ObjectOutputStream oStream;
        
        try{
            f = new File("Subscribe.dat");
            fStream = new FileOutputStream(f);
            oStream = new ObjectOutputStream(fStream);
            
            oStream.writeObject(subscriberList);
            oStream.close();
        }
        catch(IOException e){
            System.out.println(e);
        }
    }//GEN-LAST:event_UnsubscribeBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UnsubscribeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UnsubscribeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UnsubscribeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UnsubscribeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            
            // Pass arraylist with existing subscribers
            ArrayList<Subscriber> subscriberList = new ArrayList<>();
            new UnsubscribeGUI(subscriberList).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel SubscribeLbl;
    private javax.swing.JLabel ThankLbl;
    private javax.swing.JButton UnsubscribeBtn;
    private javax.swing.JLabel UnsubscribeLbl;
    // End of variables declaration//GEN-END:variables
}
